repos:
-   repo: local
    hooks:
    -   id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: This hook trims trailing whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
    -   id: end-of-file-fixer
        name: Fix End of Files
        description: Ensures that a file is either empty, or ends with one newline.
        entry: end-of-file-fixer
        language: python
        types: [text]
    -   id: isort
        name: iSort
        description: Sort imports.
        entry: isort
        args: ["--profile", "black", "--filter-files"]
        language: python
        types: [python]
    -   id: black
        name: Black
        description: Black is the uncompromising Python code formatter.
        entry: black
        language: python
        types: [python]
    -   id: flake8
        name: Flake8
        description: Flake8 ensures our code follows the standards as defined in PEP8.
        entry: flake8
        language: python
        types: [python]
        # add coverage
    # -   id: coverage
    #     name: Coverage
    #     description: Calculate unittest coverage of code.
    #     entry: coverage run --source=application -m unittest discover
    #     language: python
    #     types: [python]
    #     pass_filenames: false
    # -   id: coverage
    #     name: Coverage
    #     description: Calculate unittest coverage of code.
    #     entry: coverage-badge -f -o assets/coverage.svg
    #     language: python
    #     types: [python]
    #     pass_filenames: false
